# Generated by Django 2.2.3 on 2019-07-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
